hackathon_aki/hackathon_aki/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('client/', include('clients.urls')),
    path('catalogue/', include('platforms.urls')),
    path('catalogue_unverified/', include('administration.urls')),
    path('organizer/', include('organizers.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hackathon_aki/main/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='home'),
    path('logout/', views.logout, name='logout'),
    path('reset_password/<str:verification_code>/', views.reset_password, name='reset_password'),
    path('email_verification/<str:verification_code>/', views.email_verification, name='email_verification'),
    path('profile/<int:profile_id>/', views.show_profile, name='show_profile'),
]

hackathon_aki/organizers/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.redirect_to_organizer_profile),
    path('profile/', views.show_organizer_profile, name='show_organizer_profile'),
    path('profile/schedule/', views.show_organizer_schedule, name='show_organizer_schedule'),
    path('profile/platforms/', views.redirect_to_first_page_of_organizer_platforms, name='redirect_to_first_page_of_organizer_platforms'),
    path('profile/platforms/<int:page_id>/', views.show_organizer_platforms, name='show_organizer_platforms'),
    path('profile/platforms/add/', views.create_platform, name='create_platform'),
    path('profile/platforms/<int:platform_id>/change/', views.change_platform, name='change_platform'),
    path('profile/delete_entry/<int:platform_id>/<int:day>/<int:month>/<int:year>/', views.delete_entry, name='delete_entry'),
    path('profile/delete_registration/<int:platform_id>/<int:client_id>/<int:day>/<int:month>/<int:year>/', views.delete_registration, name='delete_registration'),
    path('profile/add_entry/<int:platform_id>/<int:day>/<int:month>/<int:year>/', views.add_entry, name='add_entry'),
    path('profile/add_registration/<int:platform_id>/<int:day>/<int:month>/<int:year>/', views.add_registration, name='add_registration'),
    path('profile/change_price/<int:platform_id>/<int:day>/<int:month>/<int:year>/', views.change_price, name='change_price'),
]

hackathon_aki/main/models.py
from django.db import models


class PasswordReset(models.Model):
    email = models.CharField('E-mail', max_length=250, blank=True)
    verification_code = models.CharField('Код подтверждения', max_length=250, unique=True, null=True)

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = 'Пароль для сброса'
        verbose_name_plural = 'Пароли для сброса'


class EmailVerification(models.Model):
    email = models.CharField('E-mail', max_length=250, blank=True)
    first_name = models.CharField('Имя', max_length=250, blank=True)
    last_name = models.CharField('Фамилия', max_length=250, blank=True)
    password = models.CharField('Пароль', max_length=250, blank=True)
    verification_code = models.CharField('Код подтверждения', max_length=250, unique=True, null=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name} {self.email}'

    class Meta:
        verbose_name = 'Не подтверждённый аккаунт'
        verbose_name_plural = 'Не подтверждённые аккаунты'


class PlatformAttachment(models.Model):
    platform = models.ForeignKey('platforms.Platform', on_delete=models.CASCADE)

    file = models.FileField('Файл')

    def __str__(self):
        return self.file.name

    class Meta:
        verbose_name = 'Закреплённый файл площадки'
        verbose_name_plural = 'Закреплённые файлы площадок'


class CommentAttachment(models.Model):
    comment = models.ForeignKey('platforms.Comment', on_delete=models.CASCADE)

    file = models.FileField('Файл')

    def __str__(self):
        return self.file.name

    class Meta:
        verbose_name = 'Закреплённый файл отзыва'
        verbose_name_plural = 'Закреплённые файлы отзывов'

hackathon_aki/organizers/models.py
from django.db import models
from django.contrib.auth.models import User
from utils import DEFAULT_SLOT_PRICE


class Organizer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    email_verification = models.OneToOneField('main.EmailVerification', on_delete=models.CASCADE, null=True, blank=True)

    middle_name = models.CharField('Отчество', max_length=250, blank=True)
    phone_number = models.CharField('Номер телефона', max_length=250, blank=True)
    position = models.CharField('Должность', max_length=250, blank=True)
    juridical_name = models.CharField('Юридическое лицо', max_length=250, blank=True)
    inn = models.CharField('ИНН', max_length=250, blank=True)

    def __str__(self):
        if self.user is not None:
            return f'{self.user.first_name} {self.user.last_name} {self.middle_name}'
        return f'Ожидание подтверждения {self.email_verification.email}'

    class Meta:
        verbose_name = 'Организатор'
        verbose_name_plural = 'Организаторы'


class Entry(models.Model):
    client = models.ForeignKey('clients.Client', on_delete=models.SET_NULL, null=True)
    platform = models.ForeignKey('platforms.Platform', on_delete=models.CASCADE)

    date = models.DateField('Дата начала записи', blank=True)
    price = models.IntegerField('Цена', default=DEFAULT_SLOT_PRICE)

    def __str__(self):
        return f'Запись на {self.date}, Клиент {self.client}'

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'

hackathon_aki/platforms/models.py
from django.db import models


class Platform(models.Model):
    organizer = models.ForeignKey('organizers.Organizer', on_delete=models.CASCADE)

    verified = models.BooleanField('Подтверждена', default=False)
    name = models.CharField('Имя', max_length=250, blank=True)
    category = models.CharField('Категория', max_length=250, blank=True)
    short_description = models.TextField('Краткое описание', blank=True)
    description = models.TextField('Описание площадки', blank=True)
    rating = models.FloatField('Рейтинг', blank=True)
    schedule = models.JSONField('Расписание', null=True, blank=True)
    address = models.JSONField('Адрес', null=True, blank=True)

    agreement = models.FileField('Соглашение', null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Площадка'
        verbose_name_plural = 'Площадки'


class Comment(models.Model):
    client = models.ForeignKey('clients.Client', on_delete=models.CASCADE)
    platform = models.ForeignKey('platforms.Platform', on_delete=models.CASCADE)

    text = models.TextField('Текст отзыва', blank=True)
    rating = models.FloatField('Рейтинг', blank=True)

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

hackathon_aki/organizers/views.py
import datetime
from django.shortcuts import render, redirect
from django.forms.models import model_to_dict
from main.models import PlatformAttachment
from platforms.models import Platform
from .models import Entry
from platforms.forms import PlatformCreatingForm, PlatformFileAttachingForm
from .forms import UserOrganizerChangingForm, ProfileOrganizerRegistrationForm
from utils import platform_categories, DEFAULT_SLOT_PRICE, SLOTS_COUNT_FOR_PLATFORM
from login_registrate_utils import process_post_forms_requests
from platforms.search_utils import search_platforms


@process_post_forms_requests
def redirect_to_organizer_profile(request, data):
    if not request.user.is_authenticated:
        return redirect('home')

    if not hasattr(request.user, 'organizer'):
        if not hasattr(request.user, 'client'):
            return redirect('home')
        return redirect('show_client_profile')

    return redirect('show_organizer_profile')


@process_post_forms_requests
def create_platform(request, data):
    if not request.user.is_authenticated or not hasattr(request.user, 'organizer'):
        return redirect('home')

    errors = {'name': [],
              'short_description': [],
              'description': [],
              'categories': [],
              'address': [],
              'agreement': []}

    if request.method == 'POST':
        is_valid = True
        if request.POST['address_text'] == '':
            errors['address'].append('Введён не корректный адрес.')
            is_valid = False

        if 'agreement' not in request.FILES:
            errors['agreement'].append('Требуется прикрепить соглашение.')
            is_valid = False

        creating_form = PlatformCreatingForm(request.POST, request.FILES)
        attachment_form = PlatformFileAttachingForm(request.POST, request.FILES)

        is_valid = creating_form.validate(errors) and is_valid
        if is_valid and attachment_form.is_valid():
            platform = creating_form.save(commit=False)
            platform.category = request.POST['platform_category']
            platform.organizer = request.user.organizer
            platform.rating = 5
            platform.address = {
                'address_text': request.POST['address_text'],
                'address_coords': [request.POST['address_latitude'], request.POST['address_longitude']],
            }
            platform.save()

            for file_description in attachment_form.cleaned_data['file_field']:
                file = PlatformAttachment(platform=platform, file=file_description)
                file.save()

            current_date = datetime.date.today()

            return redirect('show_organizer_platforms', page_id=1)

    data['errors'] = errors
    data['creating_form'] = PlatformCreatingForm()
    data['attachment_form'] = PlatformFileAttachingForm()

    data['title'] = 'Создание площадки'
    data['button_name'] = 'Создать площадку'

    return render(request, 'platforms/create_platform.html', data)


@process_post_forms_requests
def delete_entry(request, data, platform_id, day, month, year):
    if not request.user.is_authenticated:
        return redirect('show_platform_description', platform_id=platform_id)

    platform = Platform.objects.filter(id=platform_id)
    if not platform.exists():
        return redirect('show_platform_description', platform_id=platform_id)

    is_organizer = (hasattr(request.user, 'organizer') and platform.first().organizer == request.user.organizer)
    if not is_organizer:
        return redirect('show_platform_description', platform_id=platform_id)

    entry = Entry.objects.filter(platform_id=platform_id, date=datetime.date(year=year, month=month, day=day))
    if entry.exists():
        entry.first().delete()

    if "from_schedule" in request.POST:
        return redirect('show_organizer_schedule')
    if "from_client_entries" in request.POST:
        return redirect('show_client_entries')

    return redirect('show_platform_description', platform_id=platform_id)


@process_post_forms_requests
def change_price(request, data, platform_id, day, month, year):
    if not request.user.is_authenticated:
        return redirect('show_platform_description', platform_id=platform_id)

    platform = Platform.objects.filter(id=platform_id)
    if not platform.exists():
        return redirect('show_platform_description', platform_id=platform_id)

    is_organizer = (hasattr(request.user, 'organizer') and platform.first().organizer == request.user.organizer)
    if not is_organizer:
        return redirect('show_platform_description', platform_id=platform_id)

    entry = Entry.objects.filter(platform_id=platform_id, date=datetime.date(year=year, month=month, day=day))
    if entry.exists():
        new_price = request.POST['new_price']
        obj = entry.first()
        obj.price = new_price
        obj.save()

    return redirect('show_platform_description', platform_id=platform_id)


@process_post_forms_requests
def delete_registration(request, data, platform_id, client_id, day, month, year):
    if not request.user.is_authenticated:
        return redirect('show_platform_description', platform_id=platform_id)

    platform = Platform.objects.filter(id=platform_id)
    if not platform.exists():
        return redirect('show_platform_description', platform_id=platform_id)

    is_organizer = (hasattr(request.user, 'organizer') and platform.first().organizer == request.user.organizer)
    if not is_organizer:
        return redirect('show_platform_description', platform_id=platform_id)

    entry = Entry.objects.filter(platform_id=platform_id, client_id=client_id, date=datetime.date(year=year, month=month, day=day))
    if entry.exists():
        obj = entry.first()
        obj.client = None
        obj.save()

    return redirect('show_platform_description', platform_id=platform_id)


@process_post_forms_requests
def add_registration(request, data, platform_id, day, month, year):
    if not request.user.is_authenticated :
        return redirect('show_platform_description', platform_id=platform_id)

    platform = Platform.objects.filter(id=platform_id)
    if not platform.exists():
        return redirect('show_platform_description', platform_id=platform_id)

    is_client = hasattr(request.user, 'client')
    if not is_client:
        return redirect('show_platform_description', platform_id=platform_id)

    entry = Entry.objects.filter(platform_id=platform_id, date=datetime.date(year=year, month=month, day=day))
    if entry.exists():
        obj = entry.first()
        obj.client = request.user.client
        obj.save()

    return redirect('show_platform_description', platform_id=platform_id)


@process_post_forms_requests
def add_entry(request, data, platform_id, day, month, year):
    if not request.user.is_authenticated:
        return redirect('show_platform_description', platform_id=platform_id)

    platform = Platform.objects.filter(id=platform_id)
    if not platform.exists():
        return redirect('show_platform_description', platform_id=platform_id)

    is_organizer = (hasattr(request.user, 'organizer') and platform.first().organizer == request.user.organizer)
    if not is_organizer:
        return redirect('show_platform_description', platform_id=platform_id)

    entry = Entry(platform_id=platform_id, date=datetime.date(year=year, month=month, day=day))
    entry.save()

    return redirect('show_platform_description', platform_id=platform_id)


@process_post_forms_requests
def show_organizer_profile(request, data):
    if not request.user.is_authenticated:
        return redirect('home')

    if not hasattr(request.user, 'organizer'):
        if not hasattr(request.user, 'client'):
            return redirect('home')
        return redirect('show_client_profile')

    errors = {'email': [],
              'first_name': [],
              'last_name': [],
              'middle_name': [],
              'phone_number': [],
              'position': [],
              'juridical_name': [],
              'inn': []}

    if request.method == 'POST':
        user_form = UserOrganizerChangingForm(request.POST)
        profile_form = ProfileOrganizerRegistrationForm(request.POST)

        data['user_organizer_registration_form'] = user_form
        data['profile_organizer_registration_form'] = profile_form

        is_valid = user_form.validate(errors)
        is_valid = profile_form.validate(errors) and is_valid
        if is_valid:
            user = user_form.save(commit=False)
            request.user.first_name = user.first_name
            request.user.last_name = user.last_name
            request.user.save()

            user_profile = profile_form.save(commit=False)
            request.user.organizer.middle_name = user_profile.middle_name
            request.user.organizer.phone_number = user_profile.phone_number
            request.user.organizer.position = user_profile.position
            request.user.organizer.juridical_name = user_profile.juridical_name
            request.user.organizer.inn = user_profile.inn
            request.user.organizer.save()

            return redirect('show_organizer_profile')

        data['organizer_errors'] = errors
        data['has_errors'] = True
    else:
        data['user_organizer_registration_form'] = UserOrganizerChangingForm(model_to_dict(request.user))
        data['profile_organizer_registration_form'] = ProfileOrganizerRegistrationForm(
            model_to_dict(request.user.organizer))

    return render(request, 'organizers/profile.html', data)


@process_post_forms_requests
def show_organizer_schedule(request, data):
    if not request.user.is_authenticated or not hasattr(request.user, 'organizer'):
        return redirect('home')

    data['entries'] = []
    for platform in request.user.organizer.platform_set.all():
        for entry in platform.entry_set.all():
            data['entries'].append(entry)

    data['entries'].sort(key=lambda x: x.date)

hackathon_aki/organizers/templates/organizers/add_free_slot.html
{% extends 'main/html_template.html' %}

{% block title %}Создание свободного слота{% endblock %}

{% block content %}
    <form method="POST" action="">
        {% if errors.incorrect_form %}
            <p class="text-white">Некорректные данные формы</p>
        {% endif %}

        {{ form.date }} <span class="text-white">{{ errors.date }}</span> <br>
        {{ form.price }} <span class="text-white">{{ errors.price }}</span> <br>
        {% csrf_token %}
        <button type="submit">Создать</button>
    </form>
{% endblock %}

hackathon_aki/organizers/templates/organizers/profile.html
{% extends 'main/html_template.html' %}

{% load static %}

{% block title %}Профиль арендодателя{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'organizers\css\profile.css' %}">
    <script src="{% static 'organizers\js\profile.js' %}"></script>
{% endblock %}

{% block content %}
<div class="main-str">
    {% if has_errors %}
        <div style="display: none" id="form_has_errors">
        </div>
    {% endif %}

    <h1 class="text-white hat-of-profile">Мой профиль</h1>
    <br>
    <form method="POST" enctype='multipart/form-data' action="" id="profile_changing_form">
        {% if organizer_errors.incorrect_form %}
            <div class="form_alert">
                <p>Некорректные данные формы</p>
            </div>
        {% endif %}

        <div class="main-form">
            <div class="form-group">
                <label class="text-muted">Email</label>
                {{ user_organizer_registration_form.email }}
                {% for error in organizer_errors.email %}
                    <div class="form_alert">
                    {{ error }}
                    </div>
                {% endfor %}
            </div>

            <div class="form-group">
                <label class="text-muted">Фамилия</label>
                {{ user_organizer_registration_form.last_name }}
                {% for error in organizer_errors.last_name %}
                    <div class="form_alert">
                    {{ error }}
                    </div>
                {% endfor %}
            </div>

            <div class="form-group">
                <label class="text-muted">Имя</label>
                {{ user_organizer_registration_form.first_name }}
                {% for error in organizer_errors.first_name %}
                    <div class="form_alert">
                    {{ error }}
                    </div>
                {% endfor %}
            </div>

             <div class="form-group">
                <label class="text-muted">Отчество</label>
                {{ profile_organizer_registration_form.middle_name }}
                {% for error in organizer_errors.middle_name %}
                    <div class="form_alert">
                    {{ error }}
                    </div>
                {% endfor %}
            </div>

            <div class="form-group">
                <label class="text-muted">Номер телефона</label>
                {{ profile_organizer_registration_form.phone_number }}
                {% for error in organizer_errors.phone_number %}
                    <div class="form_alert">
                    {{ error }}
                    </div>
                {% endfor %}
            </div>

            <div class="form-group">
                <label class="text-muted">Позиция в компании</label>
                {{ profile_organizer_registration_form.position }}
                {% for error in organizer_errors.position %}
                    <div class="form_alert">
                    {{ error }}
                    </div>
                {% endfor %}
            </div>

            <div class="form-group">
                <label class="text-muted">Юридическое имя</label>
                {{ profile_organizer_registration_form.juridical_name }}
                {% for error in organizer_errors.juridical_name %}
                    <div class="form_alert">
                    {{ error }}
                    </div>
                {% endfor %}
            </div>

            <div class="form-group">
                <label class="text-muted">ИНН</label>
                {{ profile_organizer_registration_form.inn }}
                {% for error in organizer_errors.inn %}
                    <div class="form_alert">
                    {{ error }}
                    </div>
                {% endfor %}
            </div>

            {% csrf_token %}
            <button type="button" class="btn change-profile" id="change_profile_button">Изменить профиль</button>
        </div>
    </form>
</div>

{% endblock %}

hackathon_aki/organizers/templates/organizers/profile_platforms.html
{% extends 'main/html_template.html' %}

{% load static %}
{% load jinja_filters %}
{% load django_template_maths %}


{% block title %}Профиль арендодателя{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'organizers\css\profile_platforms.css' %}">
{% endblock %}

{% block content %}
<div class="main-str">
    <div class="hat-of-cat-prof">
        <h1 class="text-white">Мои площадки</h1>
        <form class="btn-create" action="{% url 'create_platform' %}">
            <button class="btn create-platform" type="submit">Создать площадку</button>
        </form>
    </div>


    <div class="col-6 catalog-page-org">
        {% if platforms|length > 0 %}
            <div class="container catalog-pages">
                <div class="platform">
                    {% for platform in platforms %}
                        {% if forloop.counter|sub:1|flr:15|add:1 == page_id %}
                            {% with platform_categories|key:"platform-type"|key:"filters"|key:platform.category|key:1 as card_color %}
                                <div class="col card" style="border: solid; border-color: #{{card_color}};">
                                    <div class="aspect-ratio-box-catalogue card-img-top">
                                        <img src="{{ platform.platformattachment_set.first.file.url }}" alt="{{ platform.name }}">
                                    </div>

                                    <div class="card-body">
                                        <h5 class="card-title">{{ platform.name }}</h5>
                                        <h7>{{ platform_categories|key:"platform-type"|key:"filters"|key:platform.category|key:0 }}</h7>
                                        <div class="top">
                                            <div class="img-platforms">
                                                <img src="{% static 'main\img\star-yellow.svg' %}" alt="Рейтинг">
                                            </div>
                                            <p>{{ platform.rating|round:1 }}</p>
                                            <img class="comment" src="{% static 'main\img\comment.svg' %}">
                                            <p>{{ platform.comment_set|get_all|length }}</p>
                                        </div>
                                        <div class="card-text">
                                            <p>{{ platform.short_description }}</p>
                                        </div>
                                    </div>
                                    <div class="but-in-card">
                                        <a href="{% url 'show_platform_description' platform_id=platform.id %}" class="btn">Подробнее</a>
                                    </div>
                                    {% if not platform.verified %}

                                        <p class="status">На рассмотрении</p>
                                    {% endif %}
                                </div>
                            {% endwith %}
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        {% endif %}
    </div>

    {% if all_pages|length == 0 %}
        <h3>У вас пока нет площадок.</h3>
    {% else %}
        <div class="number-of-pages">
            {% if page_id != 1 %}
                <form method="get" action="{% url 'show_organizer_platforms' page_id=page_id|sub:1 %}">
                    <input name="__filter_form" type="hidden">
                    <button type="submit">Предыдущая</button>
                    {% for filter in filters %}
                        <input type="hidden" name="{{ filter }}" value="{{ filters|key:filter }}">
                    {% endfor %}
                </form>
            {% endif %}
            {% for page_number in all_pages %}
                {% if page_number >= page_id|sub:2 and page_number <= page_id|add:2 %}
                    <form method="get" id="open_page{{page_number}}" action="{% url 'show_organizer_platforms' page_id=page_number %}">
                        <input name="__filter_form" type="hidden">
                        {% for filter in filters %}
                            <input type="hidden" name="{{ filter }}" value="{{ filters|key:filter }}">
                        {% endfor %}

                        <button class="num-page" type="submit">
                            <div class="pages" style="display: flex; ">
                                {% if page_number == all_pages|length or page_number == page_id|add:2 %}
                                    <a href="#" onclick="submitForm{{page_number}}()" style="margin-right: 0;"> {{ page_number }} </a>
                                {% else %}
                                    <a href="#" onclick="submitForm{{page_number}}()"> {{ page_number }} </a>
                                {% endif %}
                            </div>
                        </button>
                    </form>
                    <script>
                        function submitForm{{page_number}}() {
                            let form = document.getElementById("open_page{{page_number}}");
                            form.submit();
                        }
                    </script>
                {% endif %}
            {% endfor %}
            {% if page_id != all_pages|length %}
                <form method="get" action="{% url 'show_organizer_platforms' page_id=page_id|add:1 %}">
                    <input name="__filter_form" type="hidden">
                    <button type="submit">Следующая</button>
                    {% for filter in filters %}
                    <input type="hidden" name="{{ filter }}" value="{{ filters|key:filter }}">
                    {% endfor %}
                </form>
            {% endif %}
        </div>
    {% endif %}
</div>
    
{% endblock %}

hackathon_aki/organizers/templates/organizers/profile_schedule.html
{% extends 'main/html_template.html' %}

{% load static %}
{% load jinja_filters %}

{% block title %}Профиль арендодателя{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'organizers\css\profile_schedule.css' %}">
{% endblock %}

{% block content %}
<div class="text-white main-str">

    <h1 class="text-white">Расписание</h1>

    <div class="entries-block">
        <ul>
            {% for entry in entries %}
                {% if entry.client %}
                    <li>
                        <div class="entry">
                            <div class="str">
                                <p class="title-str">Дата:</p>
                                <p>{{ entry.date }}</p>
                            </div>

                            <div class="str">
                                <p class="title-str">Адрес: </p>
                                <p>{{ entry.platform.address|key:"address_text" }}</p>
                            </div>

                            <div class="str">
                                <p class="title-str">Контакты: </p>
                                <p>{{ entry.client.phone_number }}</p>
                            </div>
                            <div class="str">
                                <p class="title-str">Email: </p>
                                <p>{{ entry.client.user.email }}</p>
                            </div>
                            <div class="str">
                                <p class="title-str">Площадка: </p>
                                <p><a href="{% url 'show_platform_description' platform_id=entry.platform.id %}">{{ entry.platform.name }}</a></p>
                            </div>
                            <div class="str">
                                <p class="title-str">Цена: </p>
                                <p>{{ entry.price }} тыс. руб.</p>
                            </div>
                            <div>
                                <form method="post" action="{% url 'delete_entry' platform_id=entry.platform.id day=entry.date.day month=entry.date.month year=entry.date.year %}">
                                    <input name="from_schedule" type="hidden">
                                    {% csrf_token %}
                                    <button class="btn delete" type="submit">Удалить запись</button>
                                </form>
                            </div>
                        </div>
                    </li>
                {% endif %}
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}